name: Booking
on: [pull_request]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Run Maven compile
      run: mvn -e compile
    - name: Run tests with Maven
      run: mvn -e test