name: Booking workflow
on: [push, pull_request]
jobs:
  on-push:
    if: github.event_name == 'push' && github.triggering_actor == 'FredrikAndersson-MU24'
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo 'Push from Fredrik detected!'
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup Java 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#      - name: Run Maven compile
#        run: mvn -e compile
#      - name: Run tests with Maven
#        run: mvn -e test
  on-pull_request:
    if: github.event_name == 'pull_request' && github.ref_name == 'booking-branch'
    runs-on: ubuntu-latest
    steps:
      - name: Print Message on Pull Request
        run: echo 'Pull request detected on booking-branch!'
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup Java 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#      - name: Run Maven compile
#        run: mvn -e compile
#      - name: Run tests with Maven
#        run: mvn -e test