name: Booking workflow
on: [push, pull_request]
jobs:
  on-push:
    if: github.event_name == 'push' && github.triggering_actor == 'FredrikAndersson-MU24'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s  
          --health-timeout=5s  
          --health-retries=5
    env:
      DB_URL: jdbc:mysql://localhost:3306/test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
    steps:
      - name: Print Message
        run: echo 'Push from Fredrik detected!'
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven' # Cache for better performance?
      - name: Wait for MySQL image to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
          nc -z localhost 3306 && echo "MySQL is ready and running" && break
          sleep 2
          done
      - name: Run tests with Maven
        run: mvn --errors test
  on-pull_request:
    if: github.event_name == 'pull_request' && github.base_ref == 'booking-branch'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s  
          --health-timeout=5s  
          --health-retries=5
    env:
      DB_URL: jdbc:mysql://localhost:3306/test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
    steps:
      - name: Print Message on Pull Request
        run: echo 'Pull request on booking-branch detected!'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Wait for MySQL image to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
          nc -z localhost 3306 && echo "MySQL is ready and running" && break
          sleep 2
          done
      - name: Maven test and install
        run: mvn --debug clean install




